-- CreateEnum
CREATE TYPE "CareCategory" AS ENUM ('HOME_NURSING', 'CAREGIVER', 'ELDERLY_CARE', 'POST_HOSPITAL', 'WOUND_CARE', 'OTHER');

-- CreateEnum
CREATE TYPE "AgeBand" AS ENUM ('CHILD', 'ADULT', 'ELDERLY');

-- CreateEnum
CREATE TYPE "GenderPreference" AS ENUM ('NO_PREFERENCE', 'FEMALE', 'MALE');

-- AlterTable PatientProfile
ALTER TABLE "PatientProfile" ADD COLUMN IF NOT EXISTS "ageBand" "AgeBand" NOT NULL DEFAULT 'ADULT';
ALTER TABLE "PatientProfile" ALTER COLUMN "diagnosis" SET DEFAULT '';
ALTER TABLE "PatientProfile" ALTER COLUMN "historyHtml" SET DEFAULT '';
ALTER TABLE "PatientProfile" ALTER COLUMN "age" SET DEFAULT 0;

-- AlterTable Case
ALTER TABLE "Case" ADD COLUMN IF NOT EXISTS "category" "CareCategory" NOT NULL DEFAULT 'OTHER';
ALTER TABLE "Case" ADD COLUMN IF NOT EXISTS "ageBand" "AgeBand" NOT NULL DEFAULT 'ADULT';
ALTER TABLE "Case" ADD COLUMN IF NOT EXISTS "careSummary" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Case" ADD COLUMN IF NOT EXISTS "visitAddress" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Case" ADD COLUMN IF NOT EXISTS "visitPlaceId" TEXT;
ALTER TABLE "Case" ADD COLUMN IF NOT EXISTS "visitLat" DOUBLE PRECISION NOT NULL DEFAULT -1.286389;
ALTER TABLE "Case" ADD COLUMN IF NOT EXISTS "visitLng" DOUBLE PRECISION NOT NULL DEFAULT 36.817223;
ALTER TABLE "Case" ADD COLUMN IF NOT EXISTS "scheduledAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Case" ADD COLUMN IF NOT EXISTS "durationMinutes" INTEGER NOT NULL DEFAULT 240;
ALTER TABLE "Case" ADD COLUMN IF NOT EXISTS "genderPreference" "GenderPreference" NOT NULL DEFAULT 'NO_PREFERENCE';
ALTER TABLE "Case" ADD COLUMN IF NOT EXISTS "specialRequirements" TEXT NOT NULL DEFAULT '';

UPDATE "Case" SET "careSummary" = "wantHtml" WHERE "careSummary" = '' AND "wantHtml" <> '';

-- AlterTable Booking
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "scheduledAt" TIMESTAMP(3);
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "durationMinutes" INTEGER NOT NULL DEFAULT 240;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "visitAddress" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "visitLat" DOUBLE PRECISION NOT NULL DEFAULT -1.286389;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "visitLng" DOUBLE PRECISION NOT NULL DEFAULT 36.817223;

UPDATE "Booking" b
SET
  "scheduledAt" = c."scheduledAt",
  "durationMinutes" = c."durationMinutes",
  "visitAddress" = c."visitAddress",
  "visitLat" = c."visitLat",
  "visitLng" = c."visitLng"
FROM "Case" c
WHERE b."caseId" = c."id" AND b."scheduledAt" IS NULL;

ALTER TABLE "Booking" ALTER COLUMN "scheduledAt" SET NOT NULL;
ALTER TABLE "Booking" ALTER COLUMN "scheduledAt" SET DEFAULT CURRENT_TIMESTAMP;
